
server:
  port: 8081
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:bootexample;MODE=MySQL
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
        enable_lazy_load_no_trans: true
  jackson:
    serialization:
      write-dates-as-timestamps: true

#logging.file: classpath:/logs/api-stack-base.log
#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
#      hibernate: ERROR
